include: package:pedantic/analysis_options.yaml

analizador :
  excluir :
    - lib / **. g.dart
    - lib / presentaci贸n / i18n / **. arb
    - lib / presentaci贸n / i18n / messages_all.dart
    - lib / presentaci贸n / i18n / messages_en.dart
    - lib / presentaci贸n / i18n / messages_messages.dart
linter:
  rules:
    - avoid_print
    - avoid_returning_null

  errores :
    missing_required_param : error
